# Numpy Primer

A quick reference to some of the most common things one can do with numpy. This notebook is not meant to be comprehensive - there's always the official documentation for that. This notebook presents some of the most common usage on numpy and sets up a context for understanding how these features are used in other libraries like pandas and scipy which use numpy under the hood.


## Installation 

```pip install --upgrade numpy```

## Usage

In [3]:
import numpy as np

- A numpy uses a data structure ndarray as its core
- Create a new array using a python list
- Create an array of all zeroes or all ones by calling the respective methods
- Create an identity matrix using np.eye

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
zeros = np.zeros((3, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
ones = np.ones((3, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Basic Operations

- Create a 2D array using a list of lists
- Use the shape function to find the dimension of the array
- Use reshape to shape the array, bear in mind the product of the row and the col in the original array should be the same as the reshaped array for reshape to work.
- Use dot function to find the dot product of two array, this is not transitive and the rows of the first needs to equal the cols in the second 


In [8]:
two_d = np.array([[1, 2, 3], [4, 5, 6]])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
two_d.shape

(2, 3)

In [10]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2.reshape(4, 3)
arr2.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
A = np.array([[2, 3, 5], [1, 7, 4]])
B = np.array([[2, 5], [4, 5], [3, 9]])
np.dot(A, B)

array([[31, 70],
       [42, 76]])

## Statistical Description

- Use sum function to sum along an axis
- Use min/max to find the minimum or maximum along an axis
- Use mean, median, mode, var and std to find the respective statistical descriptors

In [12]:
numbers = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
numbers.sum(axis=0)
numbers.sum(axis=1)
numbers.min(axis=1)

array([1, 5, 9])

In [13]:
np.median(numbers, axis=0)

array([5., 6., 7., 8.])

In [14]:
salaries = np.array([[123], [225], [233], [132], [231]])
np.mean(salaries)
np.median(salaries)
np.std(salaries)
np.var(salaries)

2520.16

In [15]:
for i in numbers.flatten(order='F'):
    print ("i= {}".format(i))

i= 1
i= 5
i= 9
i= 2
i= 6
i= 10
i= 3
i= 7
i= 11
i= 4
i= 8
i= 12


In [16]:
for i in np.nditer(numbers, order='F', flags = ['external_loop']):
    print(i)

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


In [17]:
numbers.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [18]:
for i in np.nditer(numbers, op_flags = ['readwrite']):
    i[...] = i * i
    print(i)

1
4
9
16
25
36
49
64
81
100
121
144


In [19]:
numbers.ravel()

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [21]:
numbers.reshape(-1, 4)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])